#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: sqlpassword
  socket: /var/run/mysqld/mysqld.sock
  
development:
  <<: *default
  database: twitfeed

test:
  <<: *default
  database: twitfeed

production:
  <<: *default
  database: twitfeed
  username: root
  password: sqlpassword
  # password: <%= ENV['MYDEMO_DATABASE_PASSWORD'] %>