# This is a sample config file `config/application.yml` 

development:
  TWITTER_API:                  LGuAas6uV5VoBhrRWoJpPGI6F
  TWITTER_API_SECRET:           LkL1xC7QRXYbMmeM87niGdYKIxHqvvco90fJ7wO3F4bOxe8WHD
  TWITTER_ACCESS_TOKEN:         2412560971-ijJzipMBtiP7qwIH3ttSSlF505agayd8NCRfn6Y
  TWITTER_ACCESS_TOKEN_SECRET:  neTXt1tdrHazdL8TWCBKJT7IX1bDtKgAmh3ChTgpwQkXv

production:
  TWITTER_API:                  r0npLzJBZzxMLV8TYXXX7rN0O
  TWITTER_API_SECRET:           LkL1xC7QRXYbMmeM87niGdYKIxHqvvco90fJ7wO3F4bOxe8WHD
  TWITTER_ACCESS_TOKEN:         2412560971-ijJzipMBtiP7qwIH3ttSSlF505agayd8NCRfn6Y
  TWITTER_ACCESS_TOKEN_SECRET:  neTXt1tdrHazdL8TWCBKJT7IX1bDtKgAmh3ChTgpwQkXv
